export const ADD_RESERVATION = 'ADD_RESERVATION';
export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const LOADING_RESERVATION = 'LOADING_RESERVATION';
export const RESERVATION_FAILED = 'RESERVATION_FAILED';
export const GET_PATIENT_RESERVATIONS = 'GET_PATIENT_RESERVATIONS';